import { createContext, useContext } from 'react';
import type { ReactNode } from 'react';
import { createGlobalStyle } from 'styled-components';
import { globalCss } from '../tokens/css.generated';

/**
 * Injects every brand/theme token + component CSS once into the document head.
 * This lets consumers import components only — no manual `.css` imports.
 */
const GlobalTokens = createGlobalStyle`${globalCss}`;

export type Brand =
  | 'mrv'
  | 'sensia'
  | 'luggo'
  | 'mrvCo'
  | 'class'
  | 'mdc'
  | 'urba'
  | 'superApp';

export type Theme = 'light' | 'dark';

interface BrandContextValue {
  brand: Brand;
  theme: Theme;
}

const BrandContext = createContext<BrandContextValue>({ brand: 'mrv', theme: 'light' });

/** Access the current brand and theme from within a `BrandProvider`. */
export const useBrand = (): BrandContextValue => useContext(BrandContext);

export interface BrandProviderProps {
  /** Which brand theme to apply to descendant components. */
  brand: Brand;
  /** Light or dark theme. Defaults to `light`. */
  theme?: Theme;
  children: ReactNode;
  /** Optional className forwarded to the wrapper element. */
  className?: string;
}

/**
 * Applies a brand + theme to its subtree by setting `data-brand` / `data-theme`,
 * which activate the matching CSS custom properties generated by Style Dictionary.
 */
export function BrandProvider({
  brand,
  theme = 'light',
  children,
  className,
}: BrandProviderProps) {
  return (
    <BrandContext.Provider value={{ brand, theme }}>
      <GlobalTokens />
      <div data-brand={brand} data-theme={theme} className={className}>
        {children}
      </div>
    </BrandContext.Provider>
  );
}
